#!/bin/bash

if [ ! -d /mnt/tmpfs ]; then
    sudo mkdir /mnt/tmpfs
    sudo mount -t tmpfs none /mnt/tmpfs
    sudo chown larsi:users /mnt/tmpfs
fi

cd /mnt/tmpfs

while true; do
    if [ -f clock.png ]; then
	convert clock.png -type truecolor \
		+flip -strip \
		-define bmp:subtype=RGB565 \
		bmp:- | \
	    tail -c $(( 720 * 720 * 16 / 8 )) > /dev/fb0
    fi
    sleep $((60 - $(date "+%S")))
done
