#!/bin/bash

# Create a tmpfs file system for the clock images (to avoid SD card
# churn).
if [ ! -d /mnt/tmpfs ]; then
    sudo mkdir /mnt/tmpfs
fi

if ! df /mnt/tmpfs/ | grep tmpfs > /dev/null; then
    sudo mount -t tmpfs none /mnt/tmpfs
    sudo chown larsi:users /mnt/tmpfs
fi

cd /mnt/tmpfs

# Loop forever, waking up once a minute (at :00) to output a new clock
# face (pushed there from the server earlier, but with the correct time).
while true; do
    if [ -f clock.png ]; then
	# 16 bit display.
	convert clock.png -type truecolor \
		+flip -strip \
		-define bmp:subtype=RGB565 \
		bmp:- | \
	    tail -c $(( 720 * 720 * 16 / 8 )) > /dev/fb0
    fi
    sleep $((60 - $(date "+%S")))
done
